import * as Scl from "./scl.js";
import * as WhiteKeyMap from "./map.js";

const dropZone = document.getElementById("drop-zone");
  const fileInput = document.getElementById("file-input");
  const errorEl = document.getElementById("error");
  const resultEl = document.getElementById("result");
  const summaryEl = document.getElementById("summary");
  const fileNoteEl = document.getElementById("file-note");
  const startCSelect = document.getElementById("start-c");
  const downloadBtn = document.getElementById("download");
  const previewBody = document.querySelector("#preview tbody");

  let downloadName = "scale--mapped.scl";
  let downloadText = "";
  let currentParsed = null;

  WhiteKeyMap.startCOptions().forEach(function (option) {
    const el = document.createElement("option");
    el.value = String(option.midi);
    el.textContent = option.name + "  (" + option.midi + ")";
    if (option.midi === 48) el.selected = true;
    startCSelect.appendChild(el);
  });

  function startMidi() {
    return Number.parseInt(startCSelect.value, 10);
  }

  function showError(message) {
    errorEl.hidden = false;
    errorEl.textContent = message;
    resultEl.hidden = true;
    downloadBtn.disabled = true;
  }

  function clearError() {
    errorEl.hidden = true;
    errorEl.textContent = "";
  }

  function stemName(filename) {
    return filename.replace(/\.scl$/i, "") || "scale";
  }

  function renderSummary(parsed) {
    const periodToken = Scl.formatPitch(parsed.period);
    const periodCents = WhiteKeyMap.pitchToCents(parsed.period);
    summaryEl.innerHTML = "";
    const rows = [
      ["Description", parsed.description || "(none)"],
      ["Source degrees", String(parsed.n)],
      ["Source period", periodToken + "  (" + periodCents.toFixed(3) + " cents)"],
    ];
    for (const [label, value] of rows) {
      const dt = document.createElement("dt");
      dt.textContent = label;
      const dd = document.createElement("dd");
      dd.textContent = value;
      summaryEl.appendChild(dt);
      summaryEl.appendChild(dd);
    }
  }

  function renderPreview(parsed) {
    const origin = startMidi();
    const chromaticCount = WhiteKeyMap.generatedSize(parsed.n).chromaticCount;
    previewBody.innerHTML = "";
    for (let midi = 0; midi <= 127; midi++) {
      const k = midi - origin;
      const row = WhiteKeyMap.pitchAt(parsed, k);
      const tr = document.createElement("tr");
      const classes = [];
      if (row.isDuplicate) classes.push("duplicate");
      if (row.degree === 0 && !row.isDuplicate) classes.push("period-start");
      if (WhiteKeyMap.isInGeneratedCycle(k, chromaticCount)) classes.push("defined");
      tr.className = classes.join(" ");

      const cells = [
        String(midi),
        WhiteKeyMap.midiNoteName(midi),
        row.isDuplicate ? "duplicate" : String(row.whiteIndex),
        String(row.degree + 1),
        String(row.periodIndex),
        Scl.formatPitch(row.pitch),
        Scl.formatPitch(row.normalizedPitch),
      ];
      for (const text of cells) {
        const td = document.createElement("td");
        td.textContent = text;
        tr.appendChild(td);
      }
      previewBody.appendChild(tr);
    }
  }

  function buildDownload(parsed, filename) {
    const expanded = WhiteKeyMap.expand(parsed);
    const description = (parsed.description || stemName(filename)) + " (white-key mapped)";
    downloadText = Scl.serialize({
      comments: [
        stemName(filename) + "--mapped.scl",
        "Generated by Scala White-Key Mapper",
        "source: " + filename,
        "mapping: each white key advances one source degree; black keys duplicate the preceding white key",
      ],
      description,
      pitches: expanded.pitches,
    });
    downloadName = stemName(filename) + "--mapped.scl";

    fileNoteEl.textContent =
      "Generated scale: " +
      expanded.chromaticCount +
      " chromatic degrees, period = " +
      expanded.periodCount +
      " × source period.";
  }

  function handleText(text, filename) {
    try {
      const parsed = Scl.parse(text);
      currentParsed = parsed;
      clearError();
      renderSummary(parsed);
      renderPreview(parsed);
      buildDownload(parsed, filename);
      resultEl.hidden = false;
      downloadBtn.disabled = false;
    } catch (err) {
      showError(err.message || String(err));
    }
  }

  function handleFile(file) {
    if (!file) return;
    const reader = new FileReader();
    reader.onload = function () {
      handleText(String(reader.result), file.name);
    };
    reader.onerror = function () {
      showError("Could not read the file.");
    };
    reader.readAsText(file);
  }

  fileInput.addEventListener("change", function () {
    handleFile(fileInput.files[0]);
    fileInput.value = "";
  });

  dropZone.addEventListener("dragover", function (event) {
    event.preventDefault();
    dropZone.classList.add("dragover");
  });

  dropZone.addEventListener("dragleave", function () {
    dropZone.classList.remove("dragover");
  });

  dropZone.addEventListener("drop", function (event) {
    event.preventDefault();
    dropZone.classList.remove("dragover");
    const file = event.dataTransfer.files[0];
    handleFile(file);
  });

  startCSelect.addEventListener("change", function () {
    if (currentParsed) renderPreview(currentParsed);
  });

  downloadBtn.addEventListener("click", function () {
    if (!downloadText) return;
    const blob = new Blob([downloadText], { type: "text/plain" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = downloadName;
    document.body.appendChild(a);
    a.click();
    a.remove();
    URL.revokeObjectURL(url);
  });

downloadBtn.disabled = true;
